services:
  clamav:
    image: clamav/clamav:1.4.3@sha256:75fb5fd95fcbe1d7e6d240c369c1572b686ee2c95949d1042b5148de8eddebb4
    ports:
      - "3310:3310"
    volumes:
      - clamav-db:/var/lib/clamav
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3310/healthcheck || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  clamav-db:
