import { z } from 'zod'

import {
  CircuitBreakerStateSchema,
  ErrorClassSchema,
  JobStatusSchema,
  JsonValueSchema,
  OnboardingStatusSchema,
  ProfileVersionStatusSchema,
  QualityGateScopeSchema,
  QualityGateStatusSchema,
  SourceProcessingStageSchema,
  SourceTypeSchema,
  StageEventStatusSchema,
  TerminalSourceOutcomeSchema,
  TimestampSchema,
  UuidSchema,
  VerificationStatusSchema,
} from './common'

export const BusinessSchema = z.object({
  id: UuidSchema,
  workspaceId: UuidSchema,
  name: z.string().min(1),
  websiteUrl: z.string().url().nullable(),
  status: z.string(),
  createdAt: TimestampSchema,
  updatedAt: TimestampSchema,
})

export const OnboardingSessionSchema = z.object({
  id: UuidSchema,
  workspaceId: UuidSchema,
  businessId: UuidSchema,
  status: OnboardingStatusSchema,
  currentStep: z.string().nullable(),
  startedBy: UuidSchema,
  startedAt: TimestampSchema,
  completedAt: TimestampSchema.nullable(),
  error: JsonValueSchema.nullable(),
})

export const ContextSourceSchema = z.object({
  id: UuidSchema,
  workspaceId: UuidSchema,
  businessId: UuidSchema,
  sourceType: SourceTypeSchema,
  sourceName: z.string().min(1),
  externalReference: z.string().nullable(),
  status: z.string(),
  currentStage: SourceProcessingStageSchema.nullable(),
  terminalOutcome: TerminalSourceOutcomeSchema.nullable(),
  metadata: z.record(z.string(), JsonValueSchema),
  collectedAt: TimestampSchema,
})

export const SourceDocumentSchema = z.object({
  id: UuidSchema,
  workspaceId: UuidSchema,
  businessId: UuidSchema,
  sourceId: UuidSchema,
  url: z.string().url().nullable(),
  title: z.string().nullable(),
  documentType: z.string().nullable(),
  mimeType: z.string().nullable(),
  fileName: z.string().nullable(),
  fileSizeBytes: z.number().int().nonnegative().nullable(),
  contentText: z.string().nullable(),
  storagePath: z.string().nullable(),
  contentHash: z.string().min(1),
  httpStatus: z.number().int().nullable(),
  pageOrSlideCount: z.number().int().nonnegative().nullable(),
  parserName: z.string().nullable(),
  parserVersion: z.string().nullable(),
  effectiveAt: TimestampSchema.nullable(),
  supersedesDocumentId: UuidSchema.nullable(),
  metadata: z.record(z.string(), JsonValueSchema),
  retrievedAt: TimestampSchema,
})

export const ContextConflictSchema = z.object({
  id: UuidSchema,
  workspaceId: UuidSchema,
  businessId: UuidSchema,
  factKey: z.string().min(1),
  factIds: z.array(UuidSchema).min(2),
  status: z.enum(['open', 'resolved']),
  resolutionFactId: UuidSchema.nullable(),
  resolutionNote: z.string().nullable(),
  resolvedBy: UuidSchema.nullable(),
  createdAt: TimestampSchema,
  resolvedAt: TimestampSchema.nullable(),
})

export const OnboardingQuestionSchema = z.object({
  id: UuidSchema,
  workspaceId: UuidSchema,
  sessionId: UuidSchema,
  businessId: UuidSchema,
  factKey: z.string().min(1),
  questionType: z.string().min(1),
  question: z.string().min(1),
  options: JsonValueSchema.nullable(),
  reason: z.string().min(1),
  priority: z.number().int(),
  status: z.enum(['open', 'answered', 'dismissed']),
  answer: JsonValueSchema.nullable(),
  answeredBy: UuidSchema.nullable(),
  answeredAt: TimestampSchema.nullable(),
})

export const BusinessProfileVersionSchema = z.object({
  id: UuidSchema,
  workspaceId: UuidSchema,
  businessId: UuidSchema,
  version: z.number().int().positive(),
  profile: z.record(z.string(), JsonValueSchema),
  profileMarkdown: z.string().nullable(),
  status: ProfileVersionStatusSchema,
  changeSummary: z.string().nullable(),
  createdBy: UuidSchema,
  createdAt: TimestampSchema,
  approvedBy: UuidSchema.nullable(),
  approvedAt: TimestampSchema.nullable(),
})

export const ContextJobSchema = z.object({
  id: UuidSchema,
  workspaceId: UuidSchema,
  businessId: UuidSchema,
  sessionId: UuidSchema.nullable(),
  jobType: z.string().min(1),
  status: JobStatusSchema,
  attemptCount: z.number().int().nonnegative(),
  maxAttempts: z.number().int().positive(),
  idempotencyKey: z.string().min(1),
  stage: SourceProcessingStageSchema.nullable(),
  input: z.record(z.string(), JsonValueSchema),
  output: z.record(z.string(), JsonValueSchema).nullable(),
  error: JsonValueSchema.nullable(),
  errorClass: z.string().nullable(),
  retryPolicy: z.record(z.string(), JsonValueSchema),
  nextRunAt: TimestampSchema.nullable(),
  lockedBy: z.string().nullable(),
  lockedAt: TimestampSchema.nullable(),
  heartbeatAt: TimestampSchema.nullable(),
  stageTimeoutSeconds: z.number().int().positive().nullable(),
  createdAt: TimestampSchema,
  startedAt: TimestampSchema.nullable(),
  completedAt: TimestampSchema.nullable(),
})

export const ProcessingRunSchema = z.object({
  id: UuidSchema,
  workspaceId: UuidSchema,
  businessId: UuidSchema,
  sourceId: UuidSchema,
  jobId: UuidSchema.nullable(),
  pipelineType: z.string().min(1),
  status: z.string(),
  currentStage: SourceProcessingStageSchema,
  terminalOutcome: TerminalSourceOutcomeSchema.nullable(),
  attemptCount: z.number().int().nonnegative(),
  pagesProcessed: z.number().int().nonnegative(),
  slidesProcessed: z.number().int().nonnegative(),
  documentsCreated: z.number().int().nonnegative(),
  factsExtracted: z.number().int().nonnegative(),
  warningsCount: z.number().int().nonnegative(),
  creditsConsumed: z.number().nonnegative(),
  qualitySummary: z.record(z.string(), JsonValueSchema),
  startedAt: TimestampSchema,
  completedAt: TimestampSchema.nullable(),
})

export const StageEventSchema = z.object({
  id: UuidSchema,
  workspaceId: UuidSchema,
  businessId: UuidSchema,
  runId: UuidSchema,
  jobId: UuidSchema.nullable(),
  sourceId: UuidSchema,
  stage: SourceProcessingStageSchema,
  status: StageEventStatusSchema,
  attempt: z.number().int().positive(),
  workerId: z.string().nullable(),
  provider: z.string().nullable(),
  providerRequestId: z.string().nullable(),
  startedAt: TimestampSchema,
  completedAt: TimestampSchema.nullable(),
  durationMs: z.number().int().nonnegative().nullable(),
  pagesProcessed: z.number().int().nonnegative(),
  slidesProcessed: z.number().int().nonnegative(),
  bytesProcessed: z.number().int().nonnegative(),
  documentsCreated: z.number().int().nonnegative(),
  factsExtracted: z.number().int().nonnegative(),
  warningsCount: z.number().int().nonnegative(),
  creditsConsumed: z.number().nonnegative(),
  errorClass: z.string().nullable(),
  error: JsonValueSchema.nullable(),
  metadata: z.record(z.string(), JsonValueSchema),
})

export const QualityGateResultSchema = z.object({
  id: UuidSchema,
  workspaceId: UuidSchema,
  businessId: UuidSchema,
  runId: UuidSchema.nullable(),
  sourceId: UuidSchema.nullable(),
  sourceDocumentId: UuidSchema.nullable(),
  factId: UuidSchema.nullable(),
  gateScope: QualityGateScopeSchema,
  gateName: z.string().min(1),
  status: QualityGateStatusSchema,
  measuredValue: JsonValueSchema.nullable(),
  threshold: JsonValueSchema.nullable(),
  reason: z.string().nullable(),
  createdAt: TimestampSchema,
})

export const CircuitBreakerSchema = z.object({
  id: UuidSchema,
  workspaceId: UuidSchema.nullable(),
  provider: z.string().min(1),
  state: CircuitBreakerStateSchema,
  failureCount: z.number().int().nonnegative(),
  successCount: z.number().int().nonnegative(),
  timeoutCount: z.number().int().nonnegative(),
  quotaExhausted: z.boolean(),
  openedAt: TimestampSchema.nullable(),
  halfOpenAfter: TimestampSchema.nullable(),
  lastFailureAt: TimestampSchema.nullable(),
  lastSuccessAt: TimestampSchema.nullable(),
  metadata: z.record(z.string(), JsonValueSchema),
})

export const AuditLogSchema = z.object({
  id: UuidSchema,
  workspaceId: UuidSchema,
  businessId: UuidSchema,
  actorId: UuidSchema.nullable(),
  actorType: z.enum(['user', 'service', 'worker']),
  eventType: z.string().min(1),
  entityType: z.string().min(1),
  entityId: UuidSchema,
  before: z.record(z.string(), JsonValueSchema).nullable(),
  after: z.record(z.string(), JsonValueSchema).nullable(),
  createdAt: TimestampSchema,
})
